name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: initialize conda
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yaml
    - name: pytest
      run: python -m pytest