name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: initialize conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: dropsonde_test
        auto-activate-base: false
        use-mamba: true
        miniforge-version: latest
    - name: restore conda environment from cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}--${{ hashFiles('environment.yml') }}-${{ env.CONDA_CACHE_NUMBER }}
      id: conda_cache
    - name: install conda environment
      run:
        mamba env update -n dropsonde_test -f environment.yaml
      if: steps.conda_cache.outputs.cache-hit != 'true'
      id: install_conda_env
    - name: upload conda environment to cache
      uses: actions/cache/save@v4
      if: steps.install_conda_env.outcome == 'success'
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}--${{ hashFiles('environment.yml') }}-${{ env.CONDA_CACHE_NUMBER }}
    - name: install IPFS
      run: |
        wget -q https://dist.ipfs.tech/kubo/${IPFS_VERSION}/kubo_${IPFS_VERSION}_linux-amd64.tar.gz
        tar -xvzf kubo_${IPFS_VERSION}_linux-amd64.tar.gz
        pushd kubo
        sudo bash install.sh
        popd
        ipfs --version
      env:
        IPFS_VERSION: v0.32.1
    - name: init IPFS
      run: |
        ipfs init --profile server,announce-off
    - name: configure known IPFS peers
      run: |
        wget -q https://raw.githubusercontent.com/orcestra-campaign/ipfs_tools/refs/heads/main/scripts/add_peers.py -O - | python - -f https://raw.githubusercontent.com/orcestra-campaign/ipfs_tools/refs/heads/main/known_peers.yaml
    - name: run IPFS in background
      run: |
        ipfs daemon 2>ipfs.log | grep -i -o -m1 'Daemon is ready' & tail -F --pid=$! ipfs.log
    - name: run tests
      run: python -m pytest