name: test

on:
  push:
    paths:
      - 'environment.yaml'
      - 'orcestra_drop.cfg'
  pull_request: 
    paths:
      - 'environment.yaml'
      - 'orcestra_drop.cfg'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: initialize conda
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yaml
    - name: run pydropsonde 
      run: |
        cd dropsonde_data
        pydropsonde -c ../orcestra_drop.cfg
           
     
